name: tests

on: [workflow_dispatch, pull_request, merge_group, push]


env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Rust toolchain 1.81 (stable)
      run: rustup toolchain install 1.81-x86_64-unknown-linux-gnu
    - name: Lint no default features
      run: cargo clippy --all --all-targets --verbose -- -D warnings
    - name: Format
      run: cargo fmt --all --check --verbose
    - name: Build
      run: cargo build --all-targets --all --all-features --verbose
    - uses: taiki-e/install-action@nextest
    - name: Run tests
      run: cargo nextest run --verbose

